name: Bazel

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - '**bazel**'
  pull_request:
    paths:
      - '**bazel**'

jobs:
  build_embedded:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ runner.os }}-bazel

      - name: Test
        run: |
          bazelisk test //...

      - name: Build
        run: |
          bazelisk build //...
